[flags]
memory_legend = "top-left"
network_legend = "top-left"
default_widget_type = "proc"
tree = true
hide_time = true
# basic = true

[processes]
columns = ["PID", "Name", "CPU%", "Mem%", "User"]

[[row]]
  ratio=2
  [[row.child]]
    ratio=3
    type="mem"
  [[row.child]]
    ratio=4
    type="cpu"
[[row]]
  ratio=5
  [[row.child]]
    ratio=3
    [[row.child.child]]
      ratio=4
      type="net"
    [[row.child.child]]
      ratio=3
      type="disk"
    [[row.child.child]]
      ratio=3
      type="temp"
  [[row.child]]
    ratio=4
    type="proc"
