format = """
[](#769ff0)$directory[](fg:#769ff0 bg:#394260)\
$git_branch$git_status[](fg:#394260 bg:#212736)\
$rust$python[](fg:#212736 bg:#1d2230)\
$time[ ](fg:#1d2230)\
\n$character"""

[directory]
format = '[ $path ](fg:#e3e5e5 bg:#769ff0)'
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
"Documents" = '󰈙 '
"Downloads" = ' '

[git_branch]
symbol = ''
format = '[ $symbol $branch ](fg:#769ff0 bg:#394260)'

[git_status]
format = '[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)'

[rust]
symbol = 'rs'
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[python]
symbol = 'py'
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[time]
disabled = false
time_format = '%R'
format = '[  $time ](fg:#a0a9cb bg:#1d2230)'

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
